### ISSUE TITLE
Minor code cleanups

### ISSUE THREAD

**Issue by leofontenelle** [danicat/read.dbc#1]
While the code seems to be running fine, I would like to provide [a few suggestions of minor code improvements in read.dbc](https://github.com/danicat/read.dbc/files/302417/read.dbc.patch.zip):

- Raise an error if input file does not exist, so that read.dbc does not even call dbc2dbf.
- Use ``on.exit()`` to avoid nesting code.
- Raise an error if dbc2dbf returns 0.
- Avoid unnecessary ``return()``

Also, in both read.dbc and dbc2dbf I used a ``stopifnot()``, which might or might not suit your preferences.

**Comment by danicat** [comment]
Thanks for your suggestions Leo. Here are my comments:

- I'm not raising error on read.dbc because I'm leaving the low level (file access) handling to the dbc2dbf function.
- Nice idea about `on.exit()`, I may implement it sometime in the future.
- dbc2dbf returns true on success and false when not, so your code actually introduces a bug, since you have written: `if( dbc2dbf(file, out) ) stop("Could not uncompress file!")` -> you need to negate the output of dbc2dbf to treat for errors. Also, you've introduced another bug when calling `stopifnot(!file.exists(input.file))` -> please note you are negating twice.
- Finally, I prefer to use if/stop to give a more meaningful error message. The error message from `stopifnot` is something like `Error: !file.exists(input.file) is not TRUE`

I don't want to discourage you to contribute, but please be careful with the code you submit. Also, beware of over tuning / over pruning. This code is simple enough to be readable and usable. Sometimes we try to complicate simple things and take the chance to introduce bugs like those above.

**Comment by leofontenelle** [comment]
Thanks for the comments! I saw the opportunity for ``on.exit()`` and got carried away. Sorry for not testing the code before sending the suggestions, I haven't figured out how to do it yet. (Sorry for not sleeping on the suggestions either!)
